------------------------------------------ OPERATIONAL: Select Transactions Details Handled by Employee ----------------------------------------
SET linesize 380
SET pagesize 100

-- ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY';
ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-YYYY';

CREATE OR REPLACE VIEW VIEWL_ATE_EMP AS
SELECT TO_CHAR(TO_DATE(EXTRACT(MONTH FROM T.Date_Paid), 'MM'), 'MONTH') AS MONTH,
       J.JobPosition AS JOB_TYPE,
       E.EmployeeID AS EMPLOYEE_ID,
       E.EmployeeName AS EMPLOYEE_NAME,
       T.Date_Paid AS TRANS_DATE,
       T.TransactionsID AS TRANS_ID,
       T.CustomerID AS CUST_ID,
       COUNT(J.JobID) AS NUM_LATE
FROM EMPLOYEE E, JOB J, Transactions T
WHERE T.EmployeeID = E.EmployeeID AND J.JobID = E.JobID
GROUP BY TO_CHAR(TO_DATE(EXTRACT(MONTH FROM T.Date_Paid), 'MM'), 'MONTH'), J.JobPosition, E.EmployeeID, E.EmployeeName, T.Date_Paid, T.TransactionsID, T.CustomerID
ORDER BY TO_DATE(MONTH, 'MM'), T.Date_Paid;
-- SELECT * FROM VIEWL_ATE_EMP;

TTITLE CENTER "EMPLOYEE TRANSACTION RECORDS" SKIP 1-
CENTER '---------------------' SKIP 2

COLUMN MONTH FORMAT A12 HEADING 'MONTH'
COLUMN JOB_TYPE FORMAT A12 HEADING 'JOB TYPE'
COLUMN EMPLOYEE_ID FORMAT A11 HEADING 'EMPLOYEE ID'
COLUMN EMPLOYEE_NAME HEADING 'EMPLOYEE NAME'
COLUMN TRANS_DATE HEADING 'ATTENDANCE DATE'
COLUMN TRANS_ID FORMAT A14 HEADING 'TRANSACTION ID'
COLUMN CUST_ID FORMAT A11 HEADING 'CUSTOMER ID'
-- BREAK ON JOB_TYPE ON EMPLOYEE_NAME ON MONTH

BREAK ON MONTH NODUP ON JOB_TYPE NODUP ON EMPLOYEE_ID NODUP ON EMPLOYEE_NAME NODUP

CL SCR

SELECT MONTH, JOB_TYPE, EMPLOYEE_ID, EMPLOYEE_NAME, TRANS_DATE, TRANS_ID, CUST_ID
FROM VIEWL_ATE_EMP
ORDER BY TRANS_DATE;

CLEAR BREAKS
CLEAR COMPUTES
TTITLE OFF
