-- Summary Report

SET SERVEROUTPUT ON

SET PAGESIZE 600
SET LINESIZE 1200

ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-YYYY';

CREATE OR REPLACE PROCEDURE prc_monthly_purchase_report IS

CURSOR MONTH_CURSOR IS
    SELECT DISTINCT TO_CHAR(EXTRACT(YEAR FROM PT.Date_Paid)) "Year", TO_CHAR(TO_DATE(EXTRACT(MONTH FROM PT.Date_Paid), 'MM'), 'MONTH') "Month", TO_CHAR(EXTRACT(MONTH FROM Date_Paid)) "MonthNum" 
    FROM PurchaseTrans PT
    ORDER BY TO_CHAR(EXTRACT(YEAR FROM PT.Date_Paid)), TO_CHAR(EXTRACT(MONTH FROM Date_Paid));

CURSOR PURCHASE_CURSOR(v_Month NUMBER) IS
    SELECT TO_CHAR(EXTRACT(YEAR FROM Date_Paid)) "Year", TO_CHAR(TO_DATE(EXTRACT(MONTH FROM Date_Paid), 'MM'), 'MONTH') "Month", SupplierName, PurchaseTransID, Date_Paid, Total_Amt_Price
    FROM (SELECT PT.PurchaseTransID, PT.Date_Paid, S.SupplierName, SUM(Quantity * BuyPrice) AS Total_Amt_Price
          FROM Product P, Supplier S, PurchaseTrans PT, PurchaseTransDetails PTD
          WHERE S.SupplierID = PT.SupplierID AND
                PT.PurchaseTransID = PTD.PurchaseTransID AND
                PTD.ProductCode = P.ProductCode AND
                PT.PurchaseTransID = PTD.PurchaseTransID
          GROUP BY PT.PurchaseTransID, PT.Date_Paid, S.SupplierName
          ORDER BY PT.PurchaseTransID)
    WHERE TO_CHAR(EXTRACT(MONTH FROM Date_Paid)) = v_Month
    ORDER BY Date_Paid;

r_countrec NUMBER(5);
v_countrec NUMBER(5);
v_total NUMBER(11,2);

BEGIN

DBMS_OUTPUT.PUT_LINE(chr(10));
DBMS_OUTPUT.PUT_LINE(RPAD('Date',18,' ') || ':' || (SYSDATE - NUMTOYMINTERVAL(3, 'year')));
DBMS_OUTPUT.PUT_LINE(RPAD('Time', 18, ' ') || ':' || TO_CHAR(SYSDATE,'HH24:MI:SS'));
DBMS_OUTPUT.PUT_LINE(RPAD('Day',18,' ')||':'|| TO_CHAR(SYSDATE - NUMTOYMINTERVAL(3, 'year'),'DAY'));
DBMS_OUTPUT.PUT_LINE(RPAD('Generated By', 18, ' ')||':' || USER);

r_countrec := 0;
DBMS_OUTPUT.PUT_LINE(chr(10));
DBMS_OUTPUT.PUT_LINE(RPAD('*', 30, ' ') || 'Monthly Purchase Report');
DBMS_OUTPUT.PUT_LINE(RPAD('*', 30, ' ') || 'since 01-OCT-2017 to 30-JUN-2018');

FOR MONTH_REC IN MONTH_CURSOR LOOP
    DBMS_OUTPUT.PUT_LINE(chr(10));
    DBMS_OUTPUT.PUT_LINE('Month Year: ' || MONTH_REC."Month" || ' '|| MONTH_REC."Year");
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 100, '-'));
    DBMS_OUTPUT.PUT_LINE(RPAD('Purchase Transaction ID', 25, ' ') || RPAD('Date_Paid', 15, ' ') ||RPAD('Supplier Name', 40, ' ') || RPAD('Total Amount (RM)', 20, ' '));
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 100, '-'));

    v_countrec := 0;
    v_total := 0;
    
    FOR PURCHASE_REC IN PURCHASE_CURSOR(MONTH_REC."MonthNum") LOOP
 
        DBMS_OUTPUT.PUT_LINE(RPAD(PURCHASE_REC.PurchaseTransID, 25, ' ') || RPAD(PURCHASE_REC.Date_Paid, 15, ' ') || RPAD(PURCHASE_REC.SupplierName, 30, ' ') || LPAD(TO_CHAR(PURCHASE_REC.Total_Amt_Price, '999999.99'), 20, ' '));
        v_total := v_total + PURCHASE_REC.Total_Amt_Price;
        v_countrec := v_countrec + 1;
    END LOOP;

        r_countrec := r_countrec + v_countrec;
        DBMS_OUTPUT.PUT_LINE(RPAD('-', 100, '-'));
        DBMS_OUTPUT.PUT_LINE(chr(16) || 'Subtotal for purchasing products in ' || MONTH_REC."Month" || MONTH_REC."Year" || ' are RM' || TO_CHAR(v_total, '99999999.99') || ' ' || chr(17));
        DBMS_OUTPUT.PUT_LINE(chr(16) || 'Total purchase transaction done in ' || MONTH_REC."Month" || MONTH_REC."Year" || ' are ' || v_countrec || ' ' || chr(17));
        DBMS_OUTPUT.PUT_LINE(chr(10));

END LOOP;

END;
/

EXEC prc_monthly_purchase_report
